name: Deploy docs website

on:
  repository_dispatch:
    types: [build_docs]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.9.1'
      - name: Download Docs
        run:  |
          mkdir tmp
          rm -rf docs
          curl https://codeload.github.com/ClickHouse/clickhouse-docs/tar.gz/staging | tar -xz -C tmp/ --strip=2 "clickhouse-docs-staging/docs/"
          mv tmp/en docs
      - name: Download Reference Doc
        run:  |
          curl https://codeload.github.com/ClickHouse/ClickHouse/tar.gz/docs-staging | tar -xz -C tmp/ --strip=2 "ClickHouse-docs-staging/docs/"
          cp -R tmp/en docs
          cp -R tmp/ru docs/
          cp -R tmp/zh docs/
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          npm update
          npm install 
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          